### ISSUE TITLE
Input labels in train_vae.py

### ISSUE THREAD

**Issue by nabihach** [wiseodd/controlled-text-generation#12]
Line 59 in train_vae.py:
`inputs, labels = dataset.next_batch(args.gpu)`

Here, the inputs are the sentences and labels are sentiments. However, this is just a VAE, so shouldn't the labels be the same as the inputs?

**Comment by wiseodd** [comment]
You are correct. That's why, if you notice, `labels` is not being used in train_vae.py at all.
It is being used in train_discriminator.py.

**Comment by nabihach** [comment]
Ah right. Thanks!
