### ISSUE TITLE
Bug in optimizer usage

### ISSUE THREAD

**Issue by nabihach** [wiseodd/controlled-text-generation#15]
In `train_discriminator.py`, lines 78-79:
```
trainer_G = optim.Adam(model.encoder_params, lr=lr)
trainer_E = optim.Adam(model.decoder_params, lr=lr)
```
Shouldn't the names be opposite? I.e. `trainer_E` should refer to encoder's params and `trainer_G` should refer to decoder params. I guess I'm finding it a little unintuitive, that's all.

**Comment by wiseodd** [comment]
Thanks! Not only does this is unintuitive, but also this is a bug.
I have pushed the fix.
