### ISSUE TITLE
Have you made the model work yet?

### ISSUE THREAD

**Issue by zhedongzheng** [wiseodd/controlled-text-generation#5]
Hi,

I have seen two repos working on reproducing the results of this paper, but none of them is finished. It seems difficult and some details are not given in the paper.

Can I ask about your progress?

Many thanks.

**Comment by wiseodd** [comment]
Hi,

Indeed it is not that straightforward reproducing this paper.
I already have a working implementation, but I'm still tying loose ends.

I'll have it up in this repo the coming weeks. 

Cheers.
