### ISSUE TITLE
'soft' embedding

### ISSUE THREAD

**Issue by nwy2010** [wiseodd/controlled-text-generation#9]
https://github.com/wiseodd/controlled-text-generation/blob/a09ad1d9272b9e40fc0084ad1779a6d44f07862d/ctextgen/model.py#L370

this line must be 'emb = torch.mm(y.unsqueeze(0), self.word_emb.weight)'?

**Comment by wiseodd** [comment]
It corresponds to `torch.matmul` to be exact.
